---
title: "8: State Space modeller og Kalman Filteret"
subtitle: "Tidsrækkeanalyse"
author: Kasper Rosenkrands
output: 
  beamer_presentation:
    includes:
      in_header: misc/style.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE,
                      message=FALSE, warning=FALSE,
                      fig.path='figs/',
                      cache.path = '_cache/')
library(ggplot2)
library(dplyr)
library(forecast)
```

# State space modeller

Tanken bag \textbf{state space modeller} er, at vi har en skjult (latent) proces $\textbf{x}_t$ som ikke er observerbar. (\textit{Denne antages ofte af være en markovkæde}).

Grundet Markov vil der være afhængighed mellem $\textbf{x}$'erne.

Vi er interesserede i at modellere $\textbf{x}_t$, dette er dog ikke direkte muligt.

Man kan \textbf{inddirekte observere} $\textbf{x}_t$ gennem en lineær transformeret version $\textbf{y}_t$, hvor der er tilføjet støj.

Betinget på $\{ \textbf{x}_t \}_{t \in \mathbb{Z}}$ er $\textbf{y}_t$'erne uafhængige og $\textbf{y}_t$ afhænger kun af $\textbf{x}_t$

# Måleligning og tilstandsligning
Generelt skrives en state space model ud fra to ligninger. 
\begin{align*}
  \underset{p\times 1}{\vphantom{x_{t-1}}\boldsymbol x_t} &= 
  \underset{p\times p}{\vphantom{x_{t-1}}\Phi} \;\; 
  \underset{p\times 1}{\boldsymbol x_{t-1}} +  
  \underset{p\times 1}{\vphantom{x_t}\boldsymbol w_t} \tag{Tilstandsligningen}\\[2mm]
  %
  \underset{q\times 1}{\boldsymbol y_t} &= 
  \underset{q\times p}{A_t} \;\; 
  \underset{p\times 1}{\boldsymbol x_t} + 
  \underset{q\times 1}{\boldsymbol v_t} \tag{Måleligningen}
\end{align*}
Bemærk at $\boldsymbol w_t \sim \mathcal{N}_p(\boldsymbol 0,\boldsymbol Q)$ og $\boldsymbol v_t \sim \mathcal{N}_q(\boldsymbol 0,\boldsymbol R)$.

# AR(1) med støj
I en AR(1) med observationel støj har henholdsvis state-ligningen og observationsligningen formen
\begin{align*}
    &x_t=\phi x_{t-1}+w_t\\
    & y_t =x_t+v_t,
\end{align*}
hvor $\{w_t\}_{t\in\mathbb{Z}}$ og $\{v_t\}_{t\in\mathbb{Z}}$ er to uafhængige hvide støje.
Da er $\boldsymbol{\Phi}=\phi$, $\mathbf{A}_t=1$.

# Filtrering, udjævning og forecast

Formålet med at studere en state space model er at få estimeret den underliggende uobserverede proces  $\textbf{x}_t$ givet data $Y_s = \{ \textbf{y}_1, \ldots, \textbf{y}_s\}$ til tid $s$. 
\begin{itemize}
    \item Når $t > s$ så kaldes problemet forecasting
    \item Når $t=s$ kaldes problemet filtrering
    \item Når $t <s$ så kaldes probelmet smoothing
\end{itemize}

Udover estimaterne for $\textbf{x}_t$ er vi også interesseret i deres usikkerhed.

# Kalman filter
 
 Problemer af denne type kan løses vha. det såkaldte **Kalman filter**.
 
 Vi benytter følgende notation:
 \begin{itemize}
    \item $\textbf{x}_t^s = E[\textbf{x}_t | \textbf{Y}_s]$
    \item $P_{t_1, t_2}^s = E[(\textbf{x}_{t_1} - \textbf{x}_{t_1}^s)(\textbf{x}_{t_2} - \textbf{x}_{t_2}^s)^T | \textbf{Y}_s]$
    \item Når $t_1 = t_2 (=t)$ i ovenstående ligning så skrives $P_t^s$
\end{itemize}

# Fremgangsmåde
\begin{itemize}
    \item Kalman filteret er en direkte anvendelse af state space formuleringen, som tillader en estimation at blive opdateret når nye observationer er til rådighed. 
    \item Processen udføres i to dele. Den første del består i at konstruere en optimal prædiktor for den næste observation givet information op til den aktuelle tid, man nu står i. 
    \item Dette gøres vha. de såkaldte prædiktionsligninger. 
    \item Den nye observationsvektor indgår herefter i estimationen af tilstandsvektoren ved at bruge de såkaldte opdateringsligninger.\\
    \item Kalman filtret giver en optimal løsning til prædiktions og opdateringsproblemet. 
\end{itemize}

# Prædiktionsligningerne
\textbf{Prædiktionsligningerne} benyttes i første del til at konstruere en optimal prædiktor, givet information til tiden $t-1$. Ligningerne er givet ved:
\begin{align*}
    \boldsymbol x_t^{t-1} &= \Phi \boldsymbol x_{t-1}^{t-1} \\
    P_t^{t-1} &= \Phi P_{t-1}^{t-1}\Phi^\top + Q.
\end{align*}
eftersom 
\begin{align*}
  x_t^{t-1}&=\mathbb{E}(x_t|y_{t-1},y_{t-2},\dots,y_1)\\
  &= \mathbb{E}(\Phi_t x_{t-1}+w_t|y_{t-1},y_{t-2},\dots ,y_1)=\Phi x_{t-1}^{t-1}
\end{align*}
Til tid $t-1$ er al information indeholdt i $\textbf{x}_{t-1}^{t-1}$. Her vil $\textbf{x}^{t-1}_{t}$ defineres som estimatoren for $\textbf{x}_t$ til tid $t-1$

# Opdateringsligningerne

Det nye forecast af $x_t$ og $P_t$ indgår i anden del af Kalman Filteret. 
Her opnås filtrerede værdier af $x_t$, som er de værdier af $x_t$, hvor vi har information af $y$ op til tiden $t$. 
De filtrerede værdier fås ved brug af \textbf{opdateringsligninger}:
\begin{align*}
  \boldsymbol x_t^t &= \boldsymbol x_t^{t-1} + K_t \varepsilon_t \\
  P_t^t &= P_t^{t-1} - K_t A_t P_t^{t-1},
\end{align*}
hvor 
\begin{itemize}
  \item $\Sigma_t = A_tP_t^{t-1}A_t^\top + R.$
  \item $K_t = P_t^{t-1}A_t^\top\Sigma_t^{-1}.$
\end{itemize} 
$K$ kaldes for \textbf{Kalman gain}.